### ISSUE TITLE
Feature Request - Webapp for account generation

### ISSUE THREAD

**Issue by govindhh** [DigitalGlobe/DGConnect-ESRI#1]
As an analyst/developer of DGConnect-ESRI, I would like to create an account via a web link by providing required information for creating the free account. 

Acceptance Criteria:
- Input information on a web link - https://iipbeta.digitalglobe.com/accountcreation
- Receive email with username and randomly generated password
- Free account created above is ready to use

**Comment by christyberman** [comment]
Merged account creation into GBDX registration.
