### ISSUE TITLE
Can crash/freeze arcmap on aggs/uvi/catalog combination of calls

### ISSUE THREAD

**Issue by christyberman** [DigitalGlobe/DGConnect-ESRI#12]
To recreate:
1. Click UVI icon (dot plot)
2. Click Select Area and draw aoi
3. Dig in to source and geometry
4. Click Catalog icon (double square)
5. Click Select Area and draw large aoi (encompassing Syria)
6. While Catalog rows are loading, select some UVI types to download
7. While above is processing, click Aggregation icon (A in circle)
8. Click Select Area and draw aoi
9. Click Go

Result 1: since no type of call or granularity was specified, an error appears letting the user know the call cannot go through. After accepting the error, arcmap crashes.
Result 2: Can't even get beyond step 6 before freeze occurs. It takes several minutes to unfreeze.

Note: This seems to have to do with the Catalog mostly. If the user waits until Catalog has finished loading to do anything else, no freezing or crashes occur.

**Comment by wittmer85** [comment]
the steps outlined above is hitting three different sections of the code; of which anyone could be contributing to the error that is crashing/freezing arc map.  

Additionally I followed the steps above and didn't have a crash or a freezing up of ArcMap, which makes me think that the error may be specific to whatever data was being downloaded at the time.

**Comment by christyberman** [comment]
I tried it with several different types of data, so I don't believe it's the data itself. And it really only happens if I basically activate UVI, Catalog, and Aggs all at once.

**Comment by wittmer85** [comment]
does the error log show anything?

**Comment by christyberman** [comment]
I can't seem to recreate the issue now, either.

**Comment by christyberman** [comment]
Since I still can't seem to recreate this issue, I'll close it out for now and reexamine it if it actually starts occurring again.
