### ISSUE TITLE
gbd-ordering branch - have notification when order placed successfully

### ISSUE THREAD

**Issue by christyberman** [DigitalGlobe/DGConnect-ESRI#14]
There is nothing that lets a user know if the order went through successfully or not. The ui should have some way to express success and some way to express failure.

Note: I mean that the order itself was placed, not that it is completed.

**Comment by wittmer85** [comment]
this has been changed that once a order has been successfully placed to switch to the status update pane.

**Comment by christyberman** [comment]
The fix specified with switching to the order status tab after order has gone through in #13.
However, that still leaves the user unaware of orders that never go through. For large orders, it can take a long while for the order to be placed.

**Comment by christyberman** [comment]
Ordering is being completely overhauled. Ticket now obsolete, as interactions with ordering need to be completely redone.
