### ISSUE TITLE
gbd-ordering - make ordering asynchronous?

### ISSUE THREAD

**Issue by christyberman** [DigitalGlobe/DGConnect-ESRI#15]
Right now ordering basically freezes arcmap while order is processing. This is especially irritating if the order is for a large number of image strips, due to processing time.

**Comment by wittmer85** [comment]
this can be done

**Comment by giaconiamark** [comment]
I think this has to be async, due to the fact that an order could take days.

**Comment by wittmer85** [comment]
it doesn't block for days she is referring to the time it takes for gbd to setup the order which in reality we are talking seconds maybe minutes for large ones.  Once the order has been setup we have no automatic tracking of the order.  Only way through the interface to track the order is to click the refresh button on the orders page to see where in the proces the order is.

**Comment by wittmer85** [comment]
This has been fixed and changes have been uploaded to the gbd-ordering branch

**Comment by christyberman** [comment]
I no longer have to wait to issue other commands in arcmap. This is resolved for #13.

**Comment by christyberman** [comment]
Question: Does this kill the order if arcmap closes?
Question/statement: This is still sort of an issue with large orders (like say 5k strips). I don't notice any issue for smaller orders (a few hundred or less).

**Comment by wittmer85** [comment]
If arcmap closes it will most likely kill the order.  Even if the order does go through ArcMap wouldn't be running to receive the response stating that the order went through.

**Comment by christyberman** [comment]
Ordering is being completely overhauled. This ticket is now obsolete, due to needing to start over in setting up the ordering again.
