### ISSUE TITLE
Aggregations - "Go" button is now fuzzy (cosmetic issue)

### ISSUE THREAD

**Issue by christyberman** [DigitalGlobe/DGConnect-ESRI#16]
The Go button is definitely fuzzy compared to the other buttons. The calendars may also be a little fuzzy.
![fuzzy](https://cloud.githubusercontent.com/assets/10944873/11687321/0178ec38-9e54-11e5-9448-33e3f47f7bd4.PNG)

Also: it looks like MLTC tab has more height than the Change Detection tab, so MLTC drops down into the dialog area.

**Comment by wittmer85** [comment]
Issue should be closed because the form above is no longer used in the addin.  A new look/form was created several builds ago which makes this issue irrelevant.
