### ISSUE TITLE
MLTC about dialog (cosmetic issue)

### ISSUE THREAD

**Issue by eong93** [DigitalGlobe/DGConnect-ESRI#17]
Spelling mistake in the MLTC about dialog box. "br" -> "be"
![image](https://cloud.githubusercontent.com/assets/12919941/11723880/a0cf6c86-9f3e-11e5-86c1-58b6677e3605.png)

**Comment by christyberman** [comment]
![image](https://cloud.githubusercontent.com/assets/10944873/14382532/7f196d72-fd5c-11e5-82e4-5ea86c35d661.png)
