### ISSUE TITLE
Crash When Pressing Escape While Drawing RSS AOI

### ISSUE THREAD

**Issue by wittmer85** [DigitalGlobe/DGConnect-ESRI#24]
# Steps to Reproduce

1) Click RSS icon
2) Begin drawing AOI
3) While left mouse button is still down for drawing the AOI press Escape

### Crash

# What Should happen
Instead of crashing the AOI being drawn should be canceled.

**Comment by christyberman** [comment]
RSS functionality removed, so this bug is now obsolete.
