### ISSUE TITLE
Error log should include error codes along with stack traces for better debugging

### ISSUE THREAD

**Issue by christyberman** [DigitalGlobe/DGConnect-ESRI#26]
Error log found: C:\Users\username\AppData\Roaming\GBDX

Right now the error log includes the stack trace, but not the error code. This means that I can end up seeing things such as 
![besterror](https://cloud.githubusercontent.com/assets/10944873/12146749/5dfc6244-b463-11e5-8e80-8cc70763ad2b.PNG)

The above is a 504 error, although the error log does not state as much, and I had to use other debugging methods to figure out what the error was.

**Comment by wittmer85** [comment]
I believe the additional logging i added  fixes this issue.
