### ISSUE TITLE
GBDX Catalog Order - add reason for rejected status

### ISSUE THREAD

**Issue by christyberman** [DigitalGlobe/DGConnect-ESRI#27]
Right now if an order is rejected, the user has no easy way to find out why:
![butwhy](https://cloud.githubusercontent.com/assets/10944873/12156286/1cb59fdc-b498-11e5-9ad0-9087b784b77a.PNG)

Add the ability for users to see what caused the order rejection.

**Comment by christyberman** [comment]
Currently this is blocked on the front end until support is added.

**Comment by dgrason** [comment]
We will not be adding ordering through this mechanism at this time.
