### ISSUE TITLE
Can cause crash when attempting to download a large enough vector index

### ISSUE THREAD

**Issue by christyberman** [DigitalGlobe/DGConnect-ESRI#29]
To recreate:
1. Create an aoi over India (at least a large portion of it, if not all of it)
2. Use the following query: item_type:tweets item_date:[2014-10-07 TO 2015-10-07]
3. Expand points, scroll to tweets, and click to download tweets
Result: death of arcmap.

**Comment by dgrason** [comment]
@christyberman how many points does that query result in and how many do we currently claim to support for download?

**Comment by wittmer85** [comment]
we technically don't have a limit on the number we support.  The main problem with large amounts of data either lots of items or dense items we can cause a out of memory error in the current setup because we are merging all of the json pages together to make the cast to the feature class seamless.

**Comment by christyberman** [comment]
Crash no longer occurs with #85.
