### ISSUE TITLE
Socket time out crashes ArcMap

### ISSUE THREAD

**Issue by eong93** [DigitalGlobe/DGConnect-ESRI#41]
If you are attempting to download vectors from the UVI and the request times out ArcMap crashes. In the GBDX log a socket time out is recorded. This may be related to the issue where downloading several types at the same time or a type with a large amount of items #29 causes ArcMap to crash.

**Comment by christyberman** [comment]
I haven't seen socket timeouts in over a month. Attempts today have caused a socket timeout but the crash did not occur.
