### ISSUE TITLE
MLTC dialog box does not fit screen

### ISSUE THREAD

**Issue by eong93** [DigitalGlobe/DGConnect-ESRI#42]
To recreate:
1. Select several (like 100) geohashs out of 1000 lets say for the MLTC tool
2. Click Generate
3. Click yes to prompt confirming the multiple selection and computing average

You will get a dialog to confirm the values for each row which is to tall because the multiple geohash selection

![agg_bug](https://cloud.githubusercontent.com/assets/12919941/13334422/d53300b4-dbd9-11e5-92ce-298e95d21f50.PNG)

In addition to the dialog box sizing fix, maybe include a "yes to all" option

**Comment by wittmer85** [comment]
this has been fixed and merged into the master branch
