### ISSUE TITLE
Vector Upload - errors not propagated to the ui

### ISSUE THREAD

**Issue by christyberman** [DigitalGlobe/DGConnect-ESRI#48]
To recreate:
1. Upload a shapefile that is bigger than the max upload size for Tomcat (I have one that definitely works that's over 82000kb once zipped).
2. UI shows success (or at least no errors)

- Actual result: Tomcat rejects the file with an error. Nothing displays in the UI.

- Expected result: That errors gets pushed to the UI in a human-readable form.

**Comment by wittmer85** [comment]
this was corrected in commit bb8d7b9
