### ISSUE TITLE
Vector Services - need to allow use of points/linestrings as aois

### ISSUE THREAD

**Issue by christyberman** [DigitalGlobe/DGConnect-ESRI#58]
Using points/linestrings as aois doesn't work, and it should. We return vectors that intersect the aoi, so we should allow users to work with highly specific aois to see what intersects them.

To recreate:
1. Open Aggregations or Vector Services
2. Change aoi type to Selected Feature(s)
3. Select point(s)/linestring(s)
4. Go

Expected result: Search query executes. Any vectors that overlap/intersect the aoi(s) should be returned. If no vectors overlap/intersect the aoi(s), a "No data" warning should pop up.

**Comment by dgrason** [comment]
Possible solutions: prevent usage of lines/points or turn lines into bbox and add a buffer to points?

**Comment by christyberman** [comment]
Change in desired functionality calls for changing this ticket.

**Comment by wittmer85** [comment]
Aggregations was removed because the aggregation portion of the enhancement is blocked.  A new issue was created to cover the Aggregation portion of the work.

**Comment by christyberman** [comment]
This functionality has been added in the pointNline branch, to be merged to master.
