### ISSUE TITLE
Vector Services - download all crash

### ISSUE THREAD

**Issue by christyberman** [DigitalGlobe/DGConnect-ESRI#59]
To recreate:
1. In arcmap, load a polygon shapefile (use the aoi shapefile GeoInt2 provided previously). Don't bother with a basemap - just add that to the ToC and then select all the aois
2. UVI - Query: item_date:[now-1w TO now]
3. Select all 3 geometries to get the types to show up
4. Go ahead and do a download all - try polygons, for instance
Result: There's this weird hang time where nothing seems to be happening and then DEATH.

Note: If I individually select all of the vector types, crash does not occur.
Note: Maybe a thread crossing issue?

**Comment by eong93** [comment]
To recreate:
1. In ArcMap, load polygon
2. Select polygon as AOI for Vector Services
3. Check data source (GDELT), check geometry (point), Download All
Result: Incorrect download percentages and crash of ArcMap

![image](https://cloud.githubusercontent.com/assets/12919941/14817942/49a497c2-0b88-11e6-808b-f2dcdedbf3c8.png)

**Comment by christyberman** [comment]
To recreate:
1. In ArcMap, go to Rio de Janeiro in Brazil. Make an aoi using a shapefile of it or just a bounding box around it.
2. For the query, do ingest_source:Gazetteer
3. Check geometry (point), and Download All
Result: crashy crashy

Still think this is probably cross threading issue.

**Comment by christyberman** [comment]
Can't seem to get the crash anymore.
