### ISSUE TITLE
GBDX Catalog - Invalid AOI crashes ArcMap

### ISSUE THREAD

**Issue by eong93** [DigitalGlobe/DGConnect-ESRI#60]
To recreate:
1. Load map
2. Activate gbdx catalog widget
3. When drawing the aoi, just click and not drag
crash

**Comment by wittmer85** [comment]
closed by mistake

**Comment by christyberman** [comment]
Error message should be modified for clarity. Right now it reads that a user can just draw again immediately, while in actuality the user must click "Select Area" again before drawing.
