### ISSUE TITLE
Aggregations - Deleting AOI

### ISSUE THREAD

**Issue by eong93** [DigitalGlobe/DGConnect-ESRI#61]
To recreate:
1. Load map
2. Select Aggregation widget and draw AOI
3. Select AOI grapic on map and delete it
4. Click 'Go'
Result: Nothing gets returned and the Go button doesn't reactivate/never comes back

**Comment by wittmer85** [comment]
wasn't able to reproduce

**Comment by christyberman** [comment]
Now results are returned.
