### ISSUE TITLE
Catalog - wms cursor wave rechecks unchecked wms layers

### ISSUE THREAD

**Issue by christyberman** [DigitalGlobe/DGConnect-ESRI#74]
Sometimes wms gets in a state where I can uncheck the toggle for either Pan or MS, and then wave my cursor over the toggle box again and it rechecks although the wms layer doesn't add back into the ToC.

This is inconsistent behavior, because I don't always come across this.

To (potentially) recreate:
1. Open arcmap and add a layer to act as the basemap
2. Open Catalog and draw an aoi over the layer
3. Whittle down the results until you can easily find an IDAHOed catalog item
4. There is some amount of check/uncheck that is involved before the issue occurs.

Note: Actually clicking to check/uncheck again does not resolve this issue, because clicking the unchecked box once it's in this state does not actually recheck it.

**Comment by wittmer85** [comment]
currently can't reproduce anymore.  Perhaps the idaho id changes is what ended up correcting this.

**Comment by christyberman** [comment]
Testing with version 1.2.6024.21196, I have not been able to reproduce this issue.
