### ISSUE TITLE
Settings does not allow usernames with numbers

### ISSUE THREAD

**Issue by christyberman** [DigitalGlobe/DGConnect-ESRI#9]
To recreate:
1. In account management, create a user with username involving letters and numbers
2. In add-in, go to settings and try to set up the user

Result: application throws error, specifying username may only contain letters and the dot "."

**Comment by wittmer85** [comment]
issue has been fixed and will shortly be in pull request

**Comment by christyberman** [comment]
Issue fixed in #11 pull request. Closing ticket.
