### ISSUE TITLE
AnswerFactory IDAHO image reload repeatedly

### ISSUE THREAD

**Issue by christyberman** [DigitalGlobe/DGConnect-ESRI#95]
To recreate:
1. Open a project that has a lot of IDAHO images, such as Wing-a-ling-dragon.
2. Load Extract Aircrafts answer
3. After all IDAHO images and answers load, adjust how much of the screen the docked ToC takes up. Then adjust it again.
Result: all IDAHO images reload 3-5 times before settling down so that the aoi is redrawn on top of them and the answers display again.

**Comment by wittmer85** [comment]
Not a bug/issue on our end.  This is how arcmap draws the various layers.
